### ISSUE TITLE
problem with tzdata or zoneinfo

### ISSUE THREAD

**Issue by stonebig** [jupyterlite/xeus-python-demo#7]
hi,

trying to get plotnine working, I fail on a 'No time zone found with key UTC'

I can't find how to resolve this , even if trying to include tzdata

environment
```
name: xeus-python-kernel
channels:
  - https://repo.mamba.pm/emscripten-forge
  - https://repo.mamba.pm/conda-forge
dependencies:
  - ipycanvas
  - numpy
  - matplotlib
  - seaborn
  - plotnine
  - pandas
  - statsmodels
  - scikit-learn
  - scipy
  - sqlite
  - bokeh
  - panel
  - altair
  - ipympl
  - ipyleaflet
  - ipydatagrid
  - ipycanvas
  - vega_datasets
  - plotly
  - bqplot
  - black
  - pyviz_comms
  - openpyxl
  - tzdata
  - httpx
```

typical code that doesn't want to work:
````
from zoneinfo import ZoneInfo
utc = ZoneInfo('UTC')
````

target code
````
from plotnine import ggplot, geom_point, aes, stat_smooth, facet_wrap
from plotnine.data import mtcars

(ggplot(mtcars, aes('wt', 'mpg', color='factor(gear)'))
 + geom_point()
 + stat_smooth(method='lm')
 + facet_wrap('~gear'))
````

**Comment by martinRenou** [comment]
Thanks for opening an issue! 

My gut feeling is that empack is filtering out some data files from the tzdata module. I'll have a look into it.

**Comment by martinRenou** [comment]
This should fix it #53

**Comment by stonebig** [comment]
I duplicated today xeus-python-demo and generated from it a new demo2, but I still fail on it.
I don't know how to inquire.
it apparently fails also on latest jupyterlite/demo.

![image](https://user-images.githubusercontent.com/4312421/211194748-c63b3241-3883-4098-8b0a-24df91694c34.png)

**Comment by martinRenou** [comment]
It also fails that way for me with a classic JupyterLab/ipykernel/tzdata installation from conda-forge.

The issues seems to be that the [tzdata from conda-forge](https://github.com/conda-forge/tzdata-feedstock/blob/main/recipe/meta.yaml#L56) **IS NOT** the [tzdata we find on PyPi](https://pypi.org/project/tzdata). The one on conda-forge is not the Python package.

In order to install the Python one, you need to install `python-tzdata` from conda-forge. This seems to resolve the traceback you see here with the `No module named tzdata`.

But there is another issue on top of this with empack and that `python-tzdata`, I'll push a PR.

**Comment by martinRenou** [comment]
[This PR](https://github.com/emscripten-forge/empack/pull/54) fixes it, as tested in https://github.com/martinRenou/tzdata-test (https://martinrenou.github.io/tzdata-test/lab/index.html).

I'll make another empack release with this.

**Comment by stonebig** [comment]
ok, now I'm stuck on the "normal' problem of files, but otherwise, Waaaaaaaaaaaaaaa
````
FileNotFoundError: [Errno 44] No such file or directory: '/tmp/xeus-python-kernel/envs/xeus-python-kernel/lib/python3.10/site-packages/plotnine/data/mtcars.csv'
````

![image](https://user-images.githubusercontent.com/4312421/212303176-a34637a6-c994-44c3-a55d-a5c66481523b.png)

**Comment by stonebig** [comment]
My experiment was to have a full stack pytho distro... as a stupid webapp. I didn't think about the "lite" meaning, only about the dramatic simplification it apparently allows
